<nav>
    <ul>
        <li><a href="<?= $this->baseUrl() ?>/index/nojs">No JS (WTF?)</a></li>
        <li><a href="<?= $this->baseUrl() ?>/index/jquerypagination">jQuery pagination</a></li>
        <li><a href="<?= $this->baseUrl() ?>/index/closurepagination">Closure pagination</a></li>
        <li><a href="<?= $this->baseUrl() ?>/index/closurecompilation">Closure Compilation!</a></li>
        <li><a href="<?= $this->baseUrl() ?>/index/templates">Closure templates</a></li>
        <li><a href="<?= $this->baseUrl() ?>/index/stylesheets">Closure stylesheets</a></li>
        <li><a href="<?= $this->baseUrl() ?>/index/addrandomdata">Add random data to DB</a></li>
    </ul>
    <div class="clearfix"></div>
</nav>