<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Ankieta HTA</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <base href="<?php echo $this->baseUrl(); ?>" />
    <meta name="viewport" content="width=device-width">

    <link rel="stylesheet" href="<?= $this->baseUrl('/css/style.css') ?>">
    <script src="<?= $this->baseUrl('/js/libs/jit.js') ?>"></script>
</head>
<body>
<div class="container">
    <header>
        <img src="<?= $this->baseUrl('/img/top.jpg') ?>">
    </header>
    <nav id="topnav">
        <ul>
            <li><a href="<?= $this->baseUrl() ?>/internal/list">Ankiety</a></li>
            <li><a href="<?= $this->baseUrl() ?>/internal/stats">Statystyki</a></li>
            <li><a href="<?= $this->baseUrl() ?>/internal/user">Użytkownik</a></li>
            <li><a href="<?= $this->baseUrl() ?>/internal/help">Helpdesk</a></li>
            <li><?php echo $this->loggedInAs(); ?></li>
        </ul>
    </nav>
    <div>
        <?php echo $this->layout()->content; ?>
    </div>
    <footer>
        Copyright &copy; HTA Consulting 2012
    </footer>
</div>
<? // <script src="http://localhost:9810/compile?id=HTA_Admin"></script> ?>
<script src="<?= $this->baseUrl('/js/script.js') ?>"></script>

<script>
    //	var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    //	(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    //	g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    //	s.parentNode.insertBefore(g,s)}(document,'script'));
</script>

</body>
</html>
